ALTER TABLE public.models ADD COLUMN start_year integer;

ALTER TABLE public.models ADD COLUMN end_year integer;

ALTER TABLE public.intervals ADD COLUMN sequence integer;

ALTER TABLE public.intervals ADD COLUMN variables integer;

ALTER TABLE public.configurations ADD COLUMN contact character varying(100);

/*MODELS_FREQ TABLE*/
CREATE TABLE MODELS_FREQ
(
  ID BIGSERIAL NOT NULL,
  NAME TEXT NOT NULL,
  MODEL_ID BIGSERIAL NOT NULL,
  INTERVAL_ID BIGSERIAL NOT NULL,
  CREATED_AT DATE,
  UPDATED_AT DATE,  
  CONSTRAINT MODELS_FREQ_PKEY PRIMARY KEY (ID),
  CONSTRAINT FK_MODELS_FREQ_MODEL FOREIGN KEY (MODEL_ID) REFERENCES MODELS (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT FK_MODELS_FREQ_INTERVAL FOREIGN KEY (INTERVAL_ID) REFERENCES INTERVALS (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION      
)
WITH (
  OIDS=FALSE
);
ALTER TABLE MODELS_FREQ OWNER TO CPTEC;

/*RASTER DATA*/
CREATE TABLE RASTER_DATA_1
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_1_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_1 OWNER TO CPTEC;


--abaixo as demais tabelas....