ALTER TABLE public.models ADD COLUMN start_year integer;

ALTER TABLE public.models ADD COLUMN end_year integer;

ALTER TABLE public.intervals ADD COLUMN sequence integer;

ALTER TABLE public.intervals ADD COLUMN variables integer;

ALTER TABLE public.configurations ADD COLUMN contact character varying(100);

/*MODELS_FREQ TABLE*/
CREATE TABLE MODELS_FREQ
(
  ID BIGSERIAL NOT NULL,
  NAME TEXT NOT NULL,
  MODEL_ID BIGSERIAL NOT NULL,
  INTERVAL_ID BIGSERIAL NOT NULL,
  CREATED_AT DATE,
  UPDATED_AT DATE,  
  CONSTRAINT MODELS_FREQ_PKEY PRIMARY KEY (ID),
  CONSTRAINT FK_MODELS_FREQ_MODEL FOREIGN KEY (MODEL_ID) REFERENCES MODELS (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT FK_MODELS_FREQ_INTERVAL FOREIGN KEY (INTERVAL_ID) REFERENCES INTERVALS (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION      
)
WITH (
  OIDS=FALSE
);
ALTER TABLE MODELS_FREQ OWNER TO CPTEC;


/*RASTER DATA 1*/
CREATE TABLE RASTER_DATA_1
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_1_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_1 OWNER TO CPTEC;

/*RASTER DATA 2*/
CREATE TABLE RASTER_DATA_2
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_2_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_2 OWNER TO CPTEC;


/*RASTER DATA 3*/
CREATE TABLE RASTER_DATA_3
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_3_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_3 OWNER TO CPTEC;

/*RASTER DATA 4*/
CREATE TABLE RASTER_DATA_4
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_4_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_4 OWNER TO CPTEC;

/*RASTER DATA 5*/
CREATE TABLE RASTER_DATA_5
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_5_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_5 OWNER TO CPTEC;

/*RASTER DATA 6*/
CREATE TABLE RASTER_DATA_6
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_6_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_6 OWNER TO CPTEC;

/*RASTER DATA 7*/
CREATE TABLE RASTER_DATA_7
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_7_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_7 OWNER TO CPTEC;

/*RASTER DATA 8*/
CREATE TABLE RASTER_DATA_8
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_8_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_8 OWNER TO CPTEC;

/*RASTER DATA 9*/
CREATE TABLE RASTER_DATA_9
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_9_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_9 OWNER TO CPTEC;

/*RASTER DATA 10*/
CREATE TABLE RASTER_DATA_10
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_10_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_10 OWNER TO CPTEC;

/*RASTER DATA 11*/
CREATE TABLE RASTER_DATA_11
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_11_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_11 OWNER TO CPTEC;

/*RASTER DATA 12*/
CREATE TABLE RASTER_DATA_12
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_12_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_12 OWNER TO CPTEC;

/*RASTER DATA 13*/
CREATE TABLE RASTER_DATA_13
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_13_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_13 OWNER TO CPTEC;

/*RASTER DATA 14*/
CREATE TABLE RASTER_DATA_14
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_14_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_14 OWNER TO CPTEC;

/*RASTER DATA 15*/
CREATE TABLE RASTER_DATA_15
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_15_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_15 OWNER TO CPTEC;

/*RASTER DATA 16*/
CREATE TABLE RASTER_DATA_16
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_16_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_16 OWNER TO CPTEC;

/*RASTER DATA 17*/
CREATE TABLE RASTER_DATA_17
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_17_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_17 OWNER TO CPTEC;

/*RASTER DATA 18*/
CREATE TABLE RASTER_DATA_18
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_18_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_18 OWNER TO CPTEC;

/*RASTER DATA 19*/
CREATE TABLE RASTER_DATA_19
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_19_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_19 OWNER TO CPTEC;

/*RASTER DATA 20*/
CREATE TABLE RASTER_DATA_20
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_20_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_20 OWNER TO CPTEC;

/*RASTER DATA 21*/
CREATE TABLE RASTER_DATA_21
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_21_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_21 OWNER TO CPTEC;

/*RASTER DATA 22*/
CREATE TABLE RASTER_DATA_22
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_22_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_22 OWNER TO CPTEC;



/*procedure raster_data_1*/
create trigger raster_data_BI
before insert
on raster_data_1
for each row
execute procedure raster_data_BI();

/*procedure raster_data_2*/
create trigger raster_data_BI
before insert
on raster_data_2
for each row
execute procedure raster_data_BI();

/*procedure raster_data_3*/
create trigger raster_data_BI
before insert
on raster_data_3
for each row
execute procedure raster_data_BI();

/*procedure raster_data_4*/
create trigger raster_data_BI
before insert
on raster_data_4
for each row
execute procedure raster_data_BI();

/*procedure raster_data_5*/
create trigger raster_data_BI
before insert
on raster_data_5
for each row
execute procedure raster_data_BI();

/*procedure raster_data_6*/
create trigger raster_data_BI
before insert
on raster_data_6
for each row
execute procedure raster_data_BI();

/*procedure raster_data_7*/
create trigger raster_data_BI
before insert
on raster_data_7
for each row
execute procedure raster_data_BI();

/*procedure raster_data_8*/
create trigger raster_data_BI
before insert
on raster_data_8
for each row
execute procedure raster_data_BI();

/*procedure raster_data_9*/
create trigger raster_data_BI
before insert
on raster_data_9
for each row
execute procedure raster_data_BI();

/*procedure raster_data_10*/
create trigger raster_data_BI
before insert
on raster_data_10
for each row
execute procedure raster_data_BI();

/*procedure raster_data_11*/
create trigger raster_data_BI
before insert
on raster_data_11
for each row
execute procedure raster_data_BI();

/*procedure raster_data_12*/
create trigger raster_data_BI
before insert
on raster_data_12
for each row
execute procedure raster_data_BI();

/*procedure raster_data_13*/
create trigger raster_data_BI
before insert
on raster_data_13
for each row
execute procedure raster_data_BI();

/*procedure raster_data_14*/
create trigger raster_data_BI
before insert
on raster_data_14
for each row
execute procedure raster_data_BI();

/*procedure raster_data_15*/
create trigger raster_data_BI
before insert
on raster_data_15
for each row
execute procedure raster_data_BI();

/*procedure raster_data_16*/
create trigger raster_data_BI
before insert
on raster_data_16
for each row
execute procedure raster_data_BI();

/*procedure raster_data_17*/
create trigger raster_data_BI
before insert
on raster_data_17
for each row
execute procedure raster_data_BI();

/*procedure raster_data_18*/
create trigger raster_data_BI
before insert
on raster_data_18
for each row
execute procedure raster_data_BI();

/*procedure raster_data_19*/
create trigger raster_data_BI
before insert
on raster_data_19
for each row
execute procedure raster_data_BI();

/*procedure raster_data_20*/
create trigger raster_data_BI
before insert
on raster_data_20
for each row
execute procedure raster_data_BI();

/*procedure raster_data_21*/
create trigger raster_data_BI
before insert
on raster_data_21
for each row
execute procedure raster_data_BI();

/*procedure raster_data_22*/
create trigger raster_data_BI
before insert
on raster_data_22
for each row
execute procedure raster_data_BI();



INSERT INTO TYPES(NAME, EXTENSION) VALUES ('GEOJSON', '.geojson');