/*RASTER DATA 23*/
CREATE TABLE RASTER_DATA_23
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_23_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_23 OWNER TO CPTEC;

/*RASTER DATA 24*/
CREATE TABLE RASTER_DATA_24
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_24_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_24 OWNER TO CPTEC;


/*RASTER DATA 25*/
CREATE TABLE RASTER_DATA_25
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_25_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_25 OWNER TO CPTEC;

/*RASTER DATA 26*/
CREATE TABLE RASTER_DATA_26
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_26_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_26 OWNER TO CPTEC;

/*RASTER DATA 27*/
CREATE TABLE RASTER_DATA_27
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_27_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_27 OWNER TO CPTEC;

/*RASTER DATA 28*/
CREATE TABLE RASTER_DATA_28
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_28_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_28 OWNER TO CPTEC;

/*RASTER DATA 29*/
CREATE TABLE RASTER_DATA_29
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_29_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_29 OWNER TO CPTEC;

/*RASTER DATA 30*/
CREATE TABLE RASTER_DATA_30
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_30_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_30 OWNER TO CPTEC;

/*RASTER DATA 31*/
CREATE TABLE RASTER_DATA_31
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_31_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_31 OWNER TO CPTEC;

/*RASTER DATA 32*/
CREATE TABLE RASTER_DATA_32
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_32_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_32 OWNER TO CPTEC;

/*RASTER DATA 33*/
CREATE TABLE RASTER_DATA_33
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_33_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_33 OWNER TO CPTEC;

/*RASTER DATA 34*/
CREATE TABLE RASTER_DATA_34
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_34_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_34 OWNER TO CPTEC;

/*RASTER DATA 35*/
CREATE TABLE RASTER_DATA_35
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_35_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_35 OWNER TO CPTEC;

/*RASTER DATA 36*/
CREATE TABLE RASTER_DATA_36
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_36_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_36 OWNER TO CPTEC;

/*RASTER DATA 37*/
CREATE TABLE RASTER_DATA_37
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_37_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_37 OWNER TO CPTEC;

/*RASTER DATA 38*/
CREATE TABLE RASTER_DATA_38
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_38_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_38 OWNER TO CPTEC;

/*RASTER DATA 39*/
CREATE TABLE RASTER_DATA_39
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_39_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_39 OWNER TO CPTEC;

/*RASTER DATA 40*/
CREATE TABLE RASTER_DATA_40
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_40_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_40 OWNER TO CPTEC;

/*RASTER DATA 41*/
CREATE TABLE RASTER_DATA_41
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_41_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_41 OWNER TO CPTEC;

/*RASTER DATA 42*/
CREATE TABLE RASTER_DATA_42
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_42_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_42 OWNER TO CPTEC;

/*RASTER DATA 43*/
CREATE TABLE RASTER_DATA_43
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_43_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_43 OWNER TO CPTEC;

/*RASTER DATA 44*/
CREATE TABLE RASTER_DATA_44
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_44_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_44 OWNER TO CPTEC;

/*RASTER DATA 45*/
CREATE TABLE RASTER_DATA_45
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_45_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_45 OWNER TO CPTEC;

/*RASTER DATA 46*/
CREATE TABLE RASTER_DATA_46
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_46_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_46 OWNER TO CPTEC;

/*RASTER DATA 47*/
CREATE TABLE RASTER_DATA_47
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_47_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_47 OWNER TO CPTEC;

/*RASTER DATA 45*/
CREATE TABLE RASTER_DATA_48
(
  ID BIGSERIAL NOT NULL,
  DATE DATE,
  TIME TIME,
  RAST RASTER,
  FILENAME TEXT,
  MODEL CHARACTER VARYING(20),
  MODEL_COUPLED CHARACTER VARYING(20),
  SCENARIO CHARACTER VARYING(20),
  MODEL_RESOLUTION CHARACTER VARYING(10),
  ENSEMBLE CHARACTER VARYING(10),
  INTERVAL CHARACTER VARYING(10),
  VARIABLE CHARACTER VARYING(10),
  VERSION CHARACTER VARYING(2),
  CONSTRAINT RASTER_DATA_48_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RASTER_DATA_48 OWNER TO CPTEC;

/*procedure raster_data_23*/
create trigger raster_data_BI
before insert
on raster_data_23
for each row
execute procedure raster_data_BI();

/*procedure raster_data_24*/
create trigger raster_data_BI
before insert
on raster_data_24
for each row
execute procedure raster_data_BI();

/*procedure raster_data_25*/
create trigger raster_data_BI
before insert
on raster_data_25
for each row
execute procedure raster_data_BI();

/*procedure raster_data_26*/
create trigger raster_data_BI
before insert
on raster_data_26
for each row
execute procedure raster_data_BI();

/*procedure raster_data_27*/
create trigger raster_data_BI
before insert
on raster_data_27
for each row
execute procedure raster_data_BI();

/*procedure raster_data_28*/
create trigger raster_data_BI
before insert
on raster_data_28
for each row
execute procedure raster_data_BI();

/*procedure raster_data_29*/
create trigger raster_data_BI
before insert
on raster_data_29
for each row
execute procedure raster_data_BI();

/*procedure raster_data_30*/
create trigger raster_data_BI
before insert
on raster_data_30
for each row
execute procedure raster_data_BI();

/*procedure raster_data_31*/
create trigger raster_data_BI
before insert
on raster_data_31
for each row
execute procedure raster_data_BI();

/*procedure raster_data_32*/
create trigger raster_data_BI
before insert
on raster_data_32
for each row
execute procedure raster_data_BI();

/*procedure raster_data_33*/
create trigger raster_data_BI
before insert
on raster_data_33
for each row
execute procedure raster_data_BI();

/*procedure raster_data_34*/
create trigger raster_data_BI
before insert
on raster_data_34
for each row
execute procedure raster_data_BI();

/*procedure raster_data_35*/
create trigger raster_data_BI
before insert
on raster_data_35
for each row
execute procedure raster_data_BI();

/*procedure raster_data_36*/
create trigger raster_data_BI
before insert
on raster_data_36
for each row
execute procedure raster_data_BI();

/*procedure raster_data_37*/
create trigger raster_data_BI
before insert
on raster_data_37
for each row
execute procedure raster_data_BI();

/*procedure raster_data_38*/
create trigger raster_data_BI
before insert
on raster_data_38
for each row
execute procedure raster_data_BI();

/*procedure raster_data_39*/
create trigger raster_data_BI
before insert
on raster_data_39
for each row
execute procedure raster_data_BI();

/*procedure raster_data_40*/
create trigger raster_data_BI
before insert
on raster_data_40
for each row
execute procedure raster_data_BI();

/*procedure raster_data_41*/
create trigger raster_data_BI
before insert
on raster_data_41
for each row
execute procedure raster_data_BI();

/*procedure raster_data_42*/
create trigger raster_data_BI
before insert
on raster_data_42
for each row
execute procedure raster_data_BI();

/*procedure raster_data_43*/
create trigger raster_data_BI
before insert
on raster_data_43
for each row
execute procedure raster_data_BI();

/*procedure raster_data_44*/
create trigger raster_data_BI
before insert
on raster_data_44
for each row
execute procedure raster_data_BI();

/*procedure raster_data_45*/
create trigger raster_data_BI
before insert
on raster_data_45
for each row
execute procedure raster_data_BI();

/*procedure raster_data_46*/
create trigger raster_data_BI
before insert
on raster_data_46
for each row
execute procedure raster_data_BI();

/*procedure raster_data_47*/
create trigger raster_data_BI
before insert
on raster_data_47
for each row
execute procedure raster_data_BI();

/*procedure raster_data_48*/
create trigger raster_data_BI
before insert
on raster_data_48
for each row
execute procedure raster_data_BI();




INSERT INTO TYPES(NAME, EXTENSION) VALUES ('GEOJSON', '.geojson');

